# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9170bdb5a3629d267dbb1690718fcaff0d5e10b257e8d619d7ae2ec076259380c89f8a4b780a091a6dda3649bd00798621caaee35c1342642932c873c79629f6

test:
  secret_key_base: 10e90aab46420c67a7df5f9d0ca7060e1a484a9cf22b9cef30a44450f42f19566209b1f31424a4a1eb0e48ecd986f4a249e86911ea85c9712fdfe7fb8b1fad6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
